Attempt 2
```
Exception in thread "main" java.lang.NoSuchMethodError: Student.<init>(Ljava/lang/String;I)V
```

Parameters required are `java.lang.String` and `int`.

My parameters were `java.lang.String` and `java.lang.Integer`...